
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.peter.practica01.leerarchivo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLADOBLE = 22;
  public static final int DOSPUNTOS = 36;
  public static final int EXTRA = 18;
  public static final int TIPO = 16;
  public static final int SIMBOLO = 34;
  public static final int ENTERO = 32;
  public static final int UNIR = 15;
  public static final int PIE = 9;
  public static final int PORCENTAJE = 25;
  public static final int ETIQUETAS = 13;
  public static final int PUNTOCOMA = 20;
  public static final int LLAVECERRADA = 7;
  public static final int EJEY = 12;
  public static final int EJEX = 11;
  public static final int BARRAS = 8;
  public static final int PARENTESISCERRADO = 24;
  public static final int TITULO = 10;
  public static final int UMENOS = 27;
  public static final int EOF = 0;
  public static final int DECIMAL = 33;
  public static final int VALORES = 14;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int MENOS = 29;
  public static final int CORCHETECERRADO = 2;
  public static final int LLAVEABIERTA = 6;
  public static final int TOTAL = 17;
  public static final int PARENTESISABIERTO = 23;
  public static final int CANTIDAD = 26;
  public static final int DEF = 4;
  public static final int P_ERROR = 5;
  public static final int TEXTO = 35;
  public static final int DIVISION = 30;
  public static final int EJECUTAR = 19;
  public static final int CORCHETEABIERTO = 3;
  public static final int MULTIPLICACION = 31;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETECERRADO",
  "CORCHETEABIERTO",
  "DEF",
  "P_ERROR",
  "LLAVEABIERTA",
  "LLAVECERRADA",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "PUNTOCOMA",
  "COMA",
  "COMILLADOBLE",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "PORCENTAJE",
  "CANTIDAD",
  "UMENOS",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "ENTERO",
  "DECIMAL",
  "SIMBOLO",
  "TEXTO",
  "DOSPUNTOS"
  };
}

